name: Update Test Branch

on:
  push:
    branches: [main]
    
permissions: write-all

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Git User
        env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }},
        run: |
            git config user.name "${{ github.actor }}"
            git config user.email "${{ github.actor}}@users.noreply.github.com"

      - name: Update Test Branch
        run: |
          git checkout foo
          git fetch origin
          git checkout test
          git pull
          git merge --allow-unrelated-histories origin/main
          git push origin test